# Generated by Django 6.0.4 on 2026-04-28 12:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='رقم التليفون')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False, verbose_name='امر دفع')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ايجار')),
                ('salaries', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مرتبات')),
                ('spare_parts_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='شراء قطع غيار و خامات')),
                ('electricity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='كهرباء')),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مياه')),
                ('miscellaneous', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نثريات')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصنف')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('item_type', models.CharField(choices=[('spare_part', 'قطع غيار'), ('material', 'خامات')], max_length=20, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'صنف مخزن',
                'verbose_name_plural': 'المخزن',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='رقم التليفون')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفنى')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومى')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='صورة بطاقة الرقم القومى')),
            ],
            options={
                'verbose_name': 'فنى',
                'verbose_name_plural': 'الفنيين',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('license_plate', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='رقم اللوحة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('chassis_number', models.CharField(max_length=50, verbose_name='رقم الشاسيه')),
                ('engine_number', models.CharField(max_length=50, verbose_name='رقم المحرك')),
                ('car_type', models.CharField(max_length=50, verbose_name='نوع السيارة')),
                ('manufacture_year', models.IntegerField(verbose_name='سنة الصنع')),
                ('odometer_reading', models.IntegerField(verbose_name='قراءة العداد')),
                ('defects', models.TextField(blank=True, verbose_name='الاعطال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='workshop.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'سيارة',
                'verbose_name_plural': 'السيارات',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم امر الشغل')),
                ('defects', models.TextField(verbose_name='الاعطال')),
                ('labor_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المصنعيات')),
                ('spare_parts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قطع الغيار')),
                ('materials', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخامات')),
                ('status', models.CharField(choices=[('repair', 'تحت الإصلاح'), ('waiting_parts', 'انتظار قطع غيار'), ('ready', 'جاهز'), ('delivered', 'تم التسليم')], default='repair', max_length=20, verbose_name='الحالة')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workshop.car', verbose_name='السيارة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workshop.customer', verbose_name='العميل')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='workshop.technician', verbose_name='الفنى')),
            ],
            options={
                'verbose_name': 'امر شغل',
                'verbose_name_plural': 'اوامر الشغل',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('labor_costs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المصنعيات')),
                ('spare_parts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قطع الغيار')),
                ('materials', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الخامات')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='خصم (%)')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='workshop.workorder', verbose_name='امر الشغل')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
    ]
